### ISSUE TITLE
게시글 목록 페이지 관련 작업

### ISSUE THREAD

**Issue by jgjgill** [prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang#145]
## 내용 설명

게시글 목록과 관련된 작업을 진행합니다.
게시글 목록 페이지와 채널 페이지가 같은 용도입니다.
- 특정 채널에 들어가면 게시글 목록이 보인다.

[게시글 목록 페이지](https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ/%ED%98%BC%EC%BD%95-HONKOK?type=design&node-id=892-67&mode=design&t=QFma1x0MyOaF33AG-4)

## 작업 내용

- [x] 라우팅 추가
- [x] 게시물 목록 작업
- [x] 관련 스토리북 작업

## 세부 작업 기간

1일

### 채널 목록

채널 목록을 불러옵니다.

- 페이지 상단에 채널 목록을 가져오겠습니다.
- 사용되는 데이터는 채널 이름 목록입니다.

GET /channels

**Respose**

```
Channel[]
```

-> 채널 목록 페이지에서 진행 예정..!

### 특정 채널의 포스트 목록

특정 채널의 포스트 목록을 불러옵니다. 해당 api 내에 중복되는 데이터가 많지만 신경쓰지 않고 진행하겠습니다.

- 주요 기능이 될 것 같습니다.
- 무한 스크롤 훅을 사용합니다.
- 카드 컴포넌트를 사용합니다.

GET /posts/channel/{channelId}

**Request Params**

```
offset: Optional<Number>
limit: Optional<Number>
```

**Response**

```
Post[]
```

## 참고 사항

라우팅에서 다음과 같이 변경될 것 같습니다.

- 게시물 페이지: `POSTS: '/posts/:postId'` => `POST: '/posts/:postId',`로 변경
- 채널 페이지: `CHANNEL: '/channels/:channelName'` 추가

```ts
export const PATH = {
  HOME: '/',
  SIGNUP: '/signup',
  CHANNEL: '/channels/:channelName',
  POST: '/posts/:postId',
  POST_EDIT: '/post-edit',
  PROFILE: '/profile/:userId',
  FOLLOW: '/follow',
  CHAT: '/chat',
  CHAT_DETAIL: '/chat/:chatId'
};
```

**Comment by hyoribogo** [comment]
채널 리스트는 저랑 겹쳐서 안 하셔도 될 것 같아요!
