### ISSUE TITLE
메시지 관련 디자인 작업

### ISSUE THREAD

**Issue by jgjgill** [prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang#201]
## 내용 설명

메시지 관련 디자인 작업을 진행합니다.
푸터에 있는 요소라서 스타일 구현의 필요성을 느꼈습니다.

- [메시지함 페이지](https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ/%ED%98%BC%EC%BD%95-HONKOK?type=design&node-id=1214-50&mode=design&t=9y3tojhDGNlprwrG-0)
- [메시지 페이지](https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ/%ED%98%BC%EC%BD%95-HONKOK?type=design&node-id=445-1891&mode=design&t=9y3tojhDGNlprwrG-4)

## 작업 내용

- [x] 메시지함 페이지 디자인 (헤더, 푸터, 메시지 목록)
- [x] 메시지 페이지 디자인 (내가 쓴 채팅, 상대방이 쓴 채팅, 채팅 입력 창)

## 세부 작업 기간

3시간? (하기 싫어서 더 걸릴 수도 있습니다..)

**Comment by hyoribogo** [comment]
스타일 힘드시면 저에게 넘기셔도 됩니다 👍🏻
