### ISSUE TITLE
유저 스토리: 게시물 리스트 관련 작업

### ISSUE THREAD

**Issue by jgjgill** [prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang#37]
## 내용 설명

게시글 리스트 관련 작업을 진행합니다.

## 피그마 작업 페이지

- [피그마 페이지](https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ/%ED%98%BC%EC%BD%95-HONKOK?type=design&node-id=12-172&mode=design&t=HBs1ZoDq42NRaSJp-4)

## 작업 기간

7일 ~ 15일
2차 스프린트

## 세부 작업 내용
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #65 
- [x] #72 

## 사용하는 api

이슈와 관련된 api를 진행하시면 밑에 목록을 빼서 이슈로 이동시켜주세요!

### 포스트 목록 불러오기 - GET /posts/channel/{channelId}

**Request Params**

```
offset: Optional<Number>
limit: Optional<Number>
Response
```

**Response**

```
Post[]
```

### 특정 사용자 포스트 목록 불러오기 - GET /posts/author/{authorId}

**Request Params**

```
offset: Optional<Number>
limit: Optional<Number>
```

**Response**

```
Post[]
```

### 특정 포스트 상세 보기 - GET /posts/{postId}

**Response**

```
Post
```

### 내가 작성한 포스트 수정하기 - PUT /posts/update

**Request Header**

```
Authorization: bearer JWT토큰
```

**Request Body**

FormData
이미지를 삭제하려면 imageToDeletePublicId에 imagePublicId를 넣어주세요.

```
postId: String
title: String
image: Binary | null
imageToDeletePublicId: Optional
channelId: String
```

### 특정 포스트 좋아요 - POST /likes/create

**Request Header**

```
Authorization: bearer JWT토큰
```

**Request Body**

```
{
    "postId": String
}
```

**Response**

```
Like
```

### 특정 포스트 좋아요 취소 - DELETE /likes/delete

**Request Header**
```
Authorization: bearer JWT토큰
```

**Request Body**
```
{
    "id": String
}
```
**Response**
```
Like
```

**Comment by jkea1** [comment]
벳지 컴포넌트는 좋아요 버튼을 말하는게 맞을까요?

**Comment by jgjgill** [comment]
[상태 또는 속성을 표시하는 컴포넌트, Badge](https://brunch.co.kr/@leesubella/4)
이런 걸 생각했는데요!
좋아요 개수를 나타내는 것에 쓰일 수도 있고 제가 생각했던 거는 이 부분에 쓰일 것 같았습니다! https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ/%ED%98%BC%EC%BD%95-HONKOK?type=design&node-id=12-290&mode=design&t=OXI53QoTkhIEHJZO-4
