### ISSUE TITLE
아이콘 svg 관련 작업

### ISSUE THREAD

**Issue by jgjgill** [prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang#54]
## 내용 설명

아이콘을 피그마에서 커스텀하게 사용하기로 결정했습니다.
이와 관련해서 `svg`를 사용하는 방식이 여러 개 있는데 한 가지 방식으로 통일시켜 진행하면 좋을 것 같네요.
우선 제가 생각한 방향은 컴포넌트 방식입니다.

## 작업 내용

- [x] `svg` 사용 관련 코드 작성하기
- [x] 관련 내용 문서 작성하기

## 세부 작업 기간

1시간

**Comment by jkea1** [comment]
효리님이 만들어주신 아이콘 보니까 path에 `stroke` `stroke-width` `stroke-linecap` `stroke-linejoin` 값이 필수적으로 다 들어가는 거 같아서 icon 컴포넌트 조금 수정해야 할 것 같습니다.
