### ISSUE TITLE
페이지 스타일 작업

### ISSUE THREAD

**Issue by jgjgill** [prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang#85]
## 내용 설명

페이지 스타일 작업을 진행합니다.
스토리북, api 신경쓰지 말고 오로지 스타일 작업에만 집중합니다.
데이터는 사용하는 용도에 맞게 임시 `JSON` 데이터로 구성하면 될 것 같습니다.

## 피그마 작업 페이지

- [피그마 페이지](https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ/%ED%98%BC%EC%BD%95-HONKOK?type=design&node-id=330-2&mode=design&t=jYsImJNbKWuqVS9x-0)

## 작업 기간

13일 21시까지

## 세부 작업 내용

채팅은 우선순위가 낮아서 지금은 제외합니다.

- [x] #86
- [x] #88 
- [x] #87
- [x] #89 
- [x] #83
- [x] 팔로우 페이지 (건우님)
- [x] #93 

## 사용하는 api

<!-- ### GET /posts/channel/{channelId}

**Request Params**

```
offset: Optional<Number>
limit: Optional<Number>
Response
```

**Response**

```
Post[]
``` -->

<!--## 참고 사항-->

**Comment by hyoribogo** [comment]
세부 작업 내용 이슈 만들어서 가져가면 될까요 ?
